version: "3.9"

services:
  summary-app:
    build: .
    container_name: summary-app
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./samples:/app/samples
      - ./pdf_database:/app/pdf_database
    ports:
      - "8000:8000"
    command: ["sleep", "infinity"]
